### ISSUE TITLE
●	Collect all PDFs for 17,500+ Google Scholar results 

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/hosyana_review#3]
For the 17000 plus we will assign years to people. Each will get set of years to work on and load to Zotero - each works with Zotero connection and get the PDF too (to the shared folder) later export to bib 
See searching by years sheet
https://docs.google.com/spreadsheets/d/1Wz31b_jCWY_bAhFaZoCsERhvjUNxoH9npZ2MNhn0XD8/edit#gid=1791116862

**Comment by CWWhitney** [comment]
Use the search term in Google Scholar with a custom date range

“decision”+(“intervention”OR”policy”)+“uncertainty”+(“expert”OR”stakeholder”)+(“model“OR”monte carlo”OR”simulation”OR”Bayesian”OR”computer assisted”)+(“value of information”OR”information accuracy”)

2022-2023 = 2.160 results [PrajnaKARai](https://github.com/PrajnaKARai)
2020-2021 = 2.800 results [CWWhitney](https://github.com/CWWhitney)
2018-2019 = 2.420 results
2016-2017 = 2.190 results
2014-2015 = 2.060 results
etc.

<img width="360" alt="Screenshot 2023-05-25 at 17 46 01" src="https://github.com/CWWhitney/hosyana_review/assets/19190662/15981780-7b17-4c31-92de-709ee71d40c7">

**Comment by andrewm1234** [comment]
Has anybody resolved how to bypass the blockage due to suspicious activity while downloading papers while on the university VPN?

**Comment by CWWhitney** [comment]
Completed this task - all documents are now in the Zotero collection
